services:
  expo:
    build: .
    image: expo-minimal:latest
    volumes:
    - ./:/app
    - expo_node_modules:/app/node_modules
    - expo_yarn_cache:/root/.cache/yarn
    - expo_npm_cache:/root/.npm
    - expo_expo_cache:/root/.expo
    ports:
    - 19000:19000 # metro / expo dev tools
    - 19001:19001 # expo websocket
    - 19002:19002 # expo web ui
    - 8081:8081 # metro bundler
    environment:
    - EXPO_DEBUG=true
    tty: true
    stdin_open: true

volumes:
  expo_node_modules:
  expo_yarn_cache:
  expo_npm_cache:
  expo_expo_cache: